export const SITE = {
  name: 'Daniel Cerda Locksmith',
  shortName: 'DCL',
  url: 'https://dcerdalocksmith.com',
  phone: '(407) 890-4567',
  phoneHref: 'tel:+14078904567',
  email: 'info@dcerdalocksmith.com',
  address: {
    street: '151 Wildwood Dr',
    city: 'Sanford',
    state: 'FL',
    zip: '32773',
    full: '151 Wildwood Dr, Sanford, FL 32773',
    display: '151 Wildwood Dr, Sanford, FL 32773-5572',
  },
  hours: {
    display: 'Open 24/7 — 365 Days a Year',
    structured: 'Mo-Su 00:00-23:59',
  },
  geo: {
    lat: 28.8028,
    lng: -81.2681,
  },
  social: {
    facebook: 'https://www.facebook.com/danielcerdalocksmith',
    google: 'https://g.page/danielcerdalocksmith',
    yelp: 'https://www.yelp.com/biz/daniel-cerda-locksmith',
  },
  description:
    'Daniel Cerda Locksmith provides professional residential, commercial, automotive, and emergency locksmith services throughout Sanford, FL and surrounding areas. Licensed, insured, and available 24/7.',
  keywords: [
    'locksmith sanford fl',
    'emergency locksmith sanford',
    '24/7 locksmith sanford florida',
    'car lockout sanford',
    'house lockout sanford fl',
    'residential locksmith sanford',
    'commercial locksmith sanford fl',
    'automotive locksmith sanford',
    'lock repair sanford fl',
    'lock installation sanford',
    'rekeying locks sanford fl',
    'smart lock installation sanford',
    'key replacement sanford fl',
    'licensed locksmith sanford florida',
  ],
  license: 'Florida Licensed & Insured Locksmith',
  founded: '2008',
  yearsExperience: '15+',
  reviewCount: '150+',
  rating: 4.9,
  responseTime: '20-30 minutes',
  serviceRadius: '30 miles of Sanford, FL',
}

export const NAP = {
  name: SITE.name,
  address: SITE.address.display,
  phone: SITE.phone,
}

export const SCHEMA_BASE = {
  '@context': 'https://schema.org',
  '@type': ['LocalBusiness', 'Locksmith'],
  name: SITE.name,
  url: SITE.url,
  telephone: SITE.phone,
  email: SITE.email,
  address: {
    '@type': 'PostalAddress',
    streetAddress: SITE.address.street,
    addressLocality: SITE.address.city,
    addressRegion: SITE.address.state,
    postalCode: SITE.address.zip,
    addressCountry: 'US',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: SITE.geo.lat,
    longitude: SITE.geo.lng,
  },
  openingHoursSpecification: {
    '@type': 'OpeningHoursSpecification',
    dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    opens: '00:00',
    closes: '23:59',
  },
  priceRange: '$$',
  currenciesAccepted: 'USD',
  paymentAccepted: 'Cash, Credit Card, Debit Card',
  areaServed: [
    'Sanford, FL',
    'Lake Mary, FL',
    'Longwood, FL',
    'Oviedo, FL',
    'DeBary, FL',
    'Winter Springs, FL',
    'Casselberry, FL',
    'Seminole County, FL',
  ],
}
