export const SITE = {
  name: 'Daniel Cerda Locksmith',
  shortName: 'DCL',
  url: 'https://dcerdalocksmith.com',
  phone: '(575) 573-2625',
  phoneHref: 'tel:+15755732625',
  email: 'info@dcerdalocksmith.com',
  address: {
    street: '151 Wildwood Dr',
    city: 'Sanford',
    state: 'FL',
    zip: '32773',
    full: '151 Wildwood Dr, Sanford, FL 32773',
    display: '151 Wildwood Dr, Sanford, FL 32773-5572',
  },
  hours: {
    display: 'Open 24/7 — 365 Days a Year',
    structured: 'Mo-Su 00:00-23:59',
  },
  geo: {
    lat: 28.701739,
    lng: -81.3532056,
  },
  social: {
    facebook: 'https://www.facebook.com/danielcerdalocksmith',
    google: 'https://g.page/danielcerdalocksmith',
    yelp: 'https://www.yelp.com/biz/daniel-cerda-locksmith',
  },
  description:
    'Daniel Cerda Locksmith provides professional residential, commercial, automotive, and emergency locksmith services throughout Sanford, FL and surrounding areas. Licensed, insured, and available 24/7.',
  keywords: [
    // Location-specific
    'locksmith sanford fl',
    'emergency locksmith sanford',
    '24/7 locksmith sanford florida',
    'car lockout sanford',
    'house lockout sanford fl',
    'residential locksmith sanford',
    'commercial locksmith sanford fl',
    'automotive locksmith sanford',
    'lock repair sanford fl',
    'lock installation sanford',
    'rekeying locks sanford fl',
    'smart lock installation sanford',
    'key replacement sanford fl',
    'licensed locksmith sanford florida',
    // Near me — high volume
    'locksmith near me',
    'locksmith close to me',
    'emergency locksmith near me',
    '24 hour locksmith near me',
    'car locksmith near me',
    'car key replacement near me',
    'mobile locksmith near me',
    'residential locksmith near me',
    'commercial locksmith near me',
    'automotive locksmith near me',
    'auto locksmith near me',
    'lock repair near me',
    'key duplication near me',
    'locksmith near me open now',
    'local locksmith near me',
    'locksmith near sanford fl',
    // Action/intent
    'locked out of car near me',
    'house lockout near me',
    'rekey locks near me',
    'smart lock installation near me',
    'car key made near me',
  ],
  license: 'Florida Licensed & Insured Locksmith',
  founded: '2008',
  yearsExperience: '15+',
  reviewCount: '14',
  rating: 5.0,
  responseTime: '20-30 minutes',
  serviceRadius: '30 miles of Sanford, FL',
}

export const NAP = {
  name: SITE.name,
  address: SITE.address.display,
  phone: SITE.phone,
}

export const SCHEMA_BASE = {
  '@context': 'https://schema.org',
  '@type': ['LocalBusiness', 'Locksmith'],
  name: SITE.name,
  url: SITE.url,
  telephone: SITE.phone,
  email: SITE.email,
  address: {
    '@type': 'PostalAddress',
    streetAddress: SITE.address.street,
    addressLocality: SITE.address.city,
    addressRegion: SITE.address.state,
    postalCode: SITE.address.zip,
    addressCountry: 'US',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: SITE.geo.lat,
    longitude: SITE.geo.lng,
  },
  openingHoursSpecification: {
    '@type': 'OpeningHoursSpecification',
    dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    opens: '00:00',
    closes: '23:59',
  },
  priceRange: '$$',
  currenciesAccepted: 'USD',
  paymentAccepted: 'Cash, Credit Card, Debit Card',
  areaServed: [
    'Sanford, FL',
    'Lake Mary, FL',
    'Longwood, FL',
    'Oviedo, FL',
    'DeBary, FL',
    'Winter Springs, FL',
    'Casselberry, FL',
    'Seminole County, FL',
  ],
}
